version: "3"
services:
  relaybroker:
    image: gempir/relaybroker:latest
    environment:
      LOGLEVEL: error

  elasticsearch:
    image: elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xmx768m -Xms768m"
    volumes:
     - /var/es/data:/usr/share/elasticsearch/data

  echo-chamber:
    build: ./
    depends_on:
      - relaybroker
      - elasticsearch
    env_file:
      - chamber.env
    ports:
      - "1323:1323"
    environment:
      IRCHOST: relaybroker:3333
  