version: "3"
services:
  relaybroker:
    image: gempir/relaybroker:latest
    environment:
      LOGLEVEL: error

  echo-chamber:
    build: ./
    depends_on:
      - relaybroker
    env_file:
      - chamber.env
    environment:
      IRCHOST: relaybroker:3333
  